// Generated by CoffeeScript 1.8.0
(function() {
  var duplexer, spawn;

  spawn = require('child_process').spawn;

  duplexer = require('duplexer');

  module.exports = function(cmd, args) {
    var child;
    child = spawn(cmd, args);
    return duplexer(child.stdin, child.stdout);
  };

}).call(this);

//# sourceMappingURL=duplexer.js.map
