// Generated by CoffeeScript 1.8.0
(function() {
  var combine, split, through, zlib;

  combine = require('stream-combiner');

  split = require('split');

  through = require('through');

  zlib = require('zlib');

  module.exports = function() {
    var lineJson, result, tr;
    result = void 0;
    lineJson = void 0;
    tr = through(function(line) {
      if (line.length === 0) {
        return;
      }
      lineJson = JSON.parse(line);
      if (lineJson.type === "genre") {
        if (result) {
          this.queue(JSON.stringify(result) + "\n");
        }
        result = {
          name: lineJson.name,
          books: []
        };
      } else if (lineJson.type === "book") {
        result.books.push(lineJson.name);
      } else {
        console.warn("Unknown type.");
      }
    }, function() {
      if (result) {
        this.queue(JSON.stringify(result) + "\n");
      }
      this.queue(null);
    });
    return combine(split(), tr, zlib.createGzip());
  };

}).call(this);

//# sourceMappingURL=combiner.js.map
