// Generated by CoffeeScript 1.8.0
(function() {
  var http, port, server, through;

  through = require('through');

  http = require('http');

  port = 8000;

  server = function() {
    var end, write;
    write = function(buffer) {
      return this.queue(buffer.toString().toUpperCase());
    };
    end = function() {
      return this.queue(null);
    };
    return server = http.createServer(function(request, response) {
      if (request.method === 'POST') {
        return request.pipe(through(write, end)).pipe(response);
      }
    }).listen(port);
  };

  module.exports = {
    Server: server
  };

}).call(this);

//# sourceMappingURL=httpserver.js.map
