// Generated by CoffeeScript 1.8.0
(function() {
  var cipher, crypt;

  crypt = require('crypto');

  cipher = crypt.createDecipher('aes256', process.argv[2]);

  process.stdin.pipe(cipher).pipe(process.stdout);

}).call(this);

//# sourceMappingURL=crypto.js.map
