// Generated by CoffeeScript 1.8.0
(function() {
  var r, request;

  request = require('request');

  r = request.post('http://localhost:8000');

  process.stdin.pipe(r).pipe(process.stdout);

}).call(this);

//# sourceMappingURL=httpclient.js.map
