// Generated by CoffeeScript 1.8.0
(function() {
  var end, loud, through, transform, trump, trumpet, write;

  trumpet = require('trumpet');

  through = require('through');

  write = function(buffer) {
    return this.queue(buffer.toString().toUpperCase());
  };

  end = function() {
    return this.queue(null);
  };

  transform = through(write, end);

  trump = trumpet();

  loud = trump.select('.loud').createStream();

  loud.pipe(transform).pipe(loud);

  process.stdin.pipe(trump).pipe(process.stdout);

}).call(this);

//# sourceMappingURL=httpstream.js.map
