// Generated by CoffeeScript 1.8.0
(function() {
  var lineNum, split, through;

  split = require('split');

  through = require('through');

  lineNum = 1;

  process.stdin.pipe(split()).pipe(through(function(line) {
    if (lineNum % 2 === 0) {
      lineNum++;
      return console.log(line.toString().toUpperCase());
    } else {
      lineNum++;
      return console.log(line.toString().toLowerCase());
    }
  })).pipe(process.stdout);

}).call(this);

//# sourceMappingURL=split.js.map
