// Generated by CoffeeScript 1.8.0
(function() {
  var stream, ws;

  ws = require('websocket-stream');

  stream = ws('ws://localhost:8000');

  stream.write("hello\n");

}).call(this);

//# sourceMappingURL=websockets.js.map
