// Generated by CoffeeScript 1.8.0
(function() {
  function write(buffer) {var data = buffer.toString();this.queue(data.toUpperCase());};
  var end, through, tr;

  end = function() {
    return this.queue(null);
  };

  through = require('through');

  tr = through(write, end);

  process.stdin.pipe(tr).pipe(process.stdout);

}).call(this);

//# sourceMappingURL=transform.js.map
