// Generated by CoffeeScript 1.8.0
(function() {
  var duplexer, through;

  duplexer = require('duplexer');

  through = require('through');

  module.exports = function(counter) {
    var check, counts, end, write;
    counts = {};
    write = function(line) {
      return counts[line.country] = (counts[line.country] || 0) + 1;
    };
    end = function() {
      return counter.setCounts(counts);
    };
    check = through(write, end);
    return duplexer(check, counter);
  };

}).call(this);

//# sourceMappingURL=duplex2.js.map
